import type { Metadata } from "next";
import "../styles/globals.css";
import { EventProvider } from "../components/context/EventContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <EventProvider>
        <body
        className={`antialiased`}
      >
        {children}
      </body>
      </EventProvider>
      
    </html>
  );
}
