import type { Metadata } from "next";
import "../styles/globals.css";
import { UserProvider } from "@/components/context/UserContext";
// import { EventProvider } from "../components/context/EventContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <EventProvider> */}
      <UserProvider>
        <body
        className={`antialiased`}
      >
        {children}
      </body>
      </UserProvider>
        
      {/* </EventProvider> */}
      
    </html>
  );
}
